name: final_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.3.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  firebase_storage: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 

flutter:
  uses-material-design: true
